[tool.poetry]
name = "mem0ai"
version = "0.1.7"
description = "Long-term memory for AI Agents"
authors = ["Mem0 <founders@mem0.ai>"]
exclude = [
    "db",
    "configs",
    "notebooks",
    "embedchain",
]
packages = [
    { include = "mem0" },
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
qdrant-client = "^1.9.1"
pydantic = "^2.7.3"
openai = "^1.33.0"
posthog = "^3.5.0"
langchain-community = "^0.2.12"
neo4j = "^5.23.1"
peewee = "^3.17.6"
typing-extensions = "^4.12.2"
pendulum = "^3.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"
isort = "^5.13.2"
pytest = "^8.2.2"
litellm = "^1.44.5"
together = "^1.2.7"
ollama = "^0.3.1"
groq = "^0.9.0"


[tool.poetry.group.optional.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
